In [2]:
import pandas as pd

def get_average_flow_out_across_day(input_df):
    df = input_df.copy()
    
    df_weekdays = df[df['day_of_week'] < 5]
    df_weekends = df[df['day_of_week'] >= 5]

    flow_out_weekdays = df_weekdays.groupby('hour')['output_flow_rate'].mean().reset_index().rename(columns={'output_flow_rate': 'avg_weekday_output_flow'})
    flow_out_weekends = df_weekends.groupby('hour')['output_flow_rate'].mean().reset_index().rename(columns={'output_flow_rate': 'avg_weekend_output_flow'})
    
    df_combined = pd.merge(flow_out_weekdays, flow_out_weekends, on='hour', how='outer')
    
    return df_combined


def main():
    df = pd.read_parquet("../data/silver/water_consumption_silver.parquet") # fix this path
    question_2_df = get_average_flow_out_across_day(df)
    question_2_df.to_parquet("../data/gold/question_2_answer.parquet") # fix this path


if __name__ == "__main__":
    main()

In [3]:
lala = pd.read_parquet("../data/gold/question_2_answer.parquet")
lala

    hour  avg_weekday_output_flow  avg_weekend_output_flow
0      0                30.495024                32.150519
1      1                28.111094                34.569610
2      2                31.214483                23.242703
3      3                26.133140                25.231782
4      4                31.592611                21.275385
5      5                24.753829                29.900319
6      6                44.575903                28.725789
7      7                35.409079                24.665765
8      8                35.009663                16.021357
9      9                44.465926                46.060000
10    10                45.399746                50.310921
11    11                46.191390                54.663077
12    12                59.104236                60.583486
13    13                40.894010                48.343947
14    14                41.707379                41.717234
15    15                46.228893                29.444486
16    16                28.484177                40.767600
17    17                38.382426                54.240155
18    18                35.749487                45.801928
19    19                49.219389                48.237041
20    20                32.306871                62.949182
21    21                46.032493                36.618333
22    22                35.778710                36.212222
23    23                40.153469                33.221429